version: "3.8"
services:
  postgres_db:
    image: "postgres:11-alpine"
    container_name: PostgresUsers
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=adam
      - POSTGRES_PASSWORD=password
    restart: always
volumes:
  postgres_db:
    driver: local